//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.29 at 10:21:45 PM CST 
//


package com.amazonaws.mws.jaxb.entity;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ServingUnit.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ServingUnit">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="percent-fda"/>
 *     &lt;enumeration value="mg"/>
 *     &lt;enumeration value="gr"/>
 *     &lt;enumeration value="ml"/>
 *     &lt;enumeration value="grams"/>
 *     &lt;enumeration value="milligrams"/>
 *     &lt;enumeration value="milliliters"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ServingUnit")
@XmlEnum
public enum ServingUnit {

    @XmlEnumValue("percent-fda")
    PERCENT_FDA("percent-fda"),
    @XmlEnumValue("mg")
    MG("mg"),
    @XmlEnumValue("gr")
    GR("gr"),
    @XmlEnumValue("ml")
    ML("ml"),
    @XmlEnumValue("grams")
    GRAMS("grams"),
    @XmlEnumValue("milligrams")
    MILLIGRAMS("milligrams"),
    @XmlEnumValue("milliliters")
    MILLILITERS("milliliters");
    private final String value;

    ServingUnit(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ServingUnit fromValue(String v) {
        for (ServingUnit c: ServingUnit.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
