//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.29 at 10:21:45 PM CST 
//


package com.amazonaws.mws.jaxb.entity;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StoneCreationMethod.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="StoneCreationMethod">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="natural"/>
 *     &lt;enumeration value="simulated"/>
 *     &lt;enumeration value="synthetic"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "StoneCreationMethod")
@XmlEnum
public enum StoneCreationMethod {

    @XmlEnumValue("natural")
    NATURAL("natural"),
    @XmlEnumValue("simulated")
    SIMULATED("simulated"),
    @XmlEnumValue("synthetic")
    SYNTHETIC("synthetic");
    private final String value;

    StoneCreationMethod(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static StoneCreationMethod fromValue(String v) {
        for (StoneCreationMethod c: StoneCreationMethod.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
