//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.29 at 10:21:45 PM CST 
//


package com.amazonaws.mws.entity.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AirFlowDisplacementUnitOfMeasure.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AirFlowDisplacementUnitOfMeasure">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="cubic_feet_per_minute"/>
 *     &lt;enumeration value="cubic_feet_per_hour"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AirFlowDisplacementUnitOfMeasure")
@XmlEnum
public enum AirFlowDisplacementUnitOfMeasure {

    @XmlEnumValue("cubic_feet_per_minute")
    CUBIC_FEET_PER_MINUTE("cubic_feet_per_minute"),
    @XmlEnumValue("cubic_feet_per_hour")
    CUBIC_FEET_PER_HOUR("cubic_feet_per_hour");
    private final String value;

    AirFlowDisplacementUnitOfMeasure(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AirFlowDisplacementUnitOfMeasure fromValue(String v) {
        for (AirFlowDisplacementUnitOfMeasure c: AirFlowDisplacementUnitOfMeasure.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
