//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.29 at 10:21:45 PM CST 
//


package com.amazonaws.mws.entity.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DegreeUnitOfMeasure.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DegreeUnitOfMeasure">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="degrees"/>
 *     &lt;enumeration value="microradian"/>
 *     &lt;enumeration value="arc_minute"/>
 *     &lt;enumeration value="arc_sec"/>
 *     &lt;enumeration value="milliradian"/>
 *     &lt;enumeration value="radians"/>
 *     &lt;enumeration value="turns"/>
 *     &lt;enumeration value="revolutions"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DegreeUnitOfMeasure")
@XmlEnum
public enum DegreeUnitOfMeasure {

    @XmlEnumValue("degrees")
    DEGREES("degrees"),
    @XmlEnumValue("microradian")
    MICRORADIAN("microradian"),
    @XmlEnumValue("arc_minute")
    ARC_MINUTE("arc_minute"),
    @XmlEnumValue("arc_sec")
    ARC_SEC("arc_sec"),
    @XmlEnumValue("milliradian")
    MILLIRADIAN("milliradian"),
    @XmlEnumValue("radians")
    RADIANS("radians"),
    @XmlEnumValue("turns")
    TURNS("turns"),
    @XmlEnumValue("revolutions")
    REVOLUTIONS("revolutions");
    private final String value;

    DegreeUnitOfMeasure(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DegreeUnitOfMeasure fromValue(String v) {
        for (DegreeUnitOfMeasure c: DegreeUnitOfMeasure.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
