//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.29 at 10:21:45 PM CST 
//


package com.amazonaws.mws.entity.jaxb;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.amazonaws.mws.entity.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ConditionType_QNAME = new QName("", "ConditionType");
    private final static QName _AmazonOrderItemCode_QNAME = new QName("", "AmazonOrderItemCode");
    private final static QName _ProductTaxCode_QNAME = new QName("", "ProductTaxCode");
    private final static QName _CharacterData_QNAME = new QName("", "CharacterData");
    private final static QName _AmazonOrderID_QNAME = new QName("", "AmazonOrderID");
    private final static QName _MerchantOrderItemID_QNAME = new QName("", "MerchantOrderItemID");
    private final static QName _Denomination_QNAME = new QName("", "Denomination");
    private final static QName _MerchantPromotionID_QNAME = new QName("", "MerchantPromotionID");
    private final static QName _SKU_QNAME = new QName("", "SKU");
    private final static QName _AmazonCustomerID_QNAME = new QName("", "AmazonCustomerID");
    private final static QName _ColorMap_QNAME = new QName("", "ColorMap");
    private final static QName _ShipmentID_QNAME = new QName("", "ShipmentID");
    private final static QName _MerchantFulfillmentID_QNAME = new QName("", "MerchantFulfillmentID");
    private final static QName _CarrierCode_QNAME = new QName("", "CarrierCode");
    private final static QName _FulfillmentMethod_QNAME = new QName("", "FulfillmentMethod");
    private final static QName _FulfillmentCenterID_QNAME = new QName("", "FulfillmentCenterID");
    private final static QName _PromotionClaimCode_QNAME = new QName("", "PromotionClaimCode");
    private final static QName _ShipOption_QNAME = new QName("", "ShipOption");
    private final static QName _ExternalCustomerID_QNAME = new QName("", "ExternalCustomerID");
    private final static QName _Address_QNAME = new QName("", "Address");
    private final static QName _MarketplaceName_QNAME = new QName("", "MarketplaceName");
    private final static QName _MerchantOrderID_QNAME = new QName("", "MerchantOrderID");
    private final static QName _FulfillmentServiceLevel_QNAME = new QName("", "FulfillmentServiceLevel");
    private final static QName _DeliveryChannel_QNAME = new QName("", "DeliveryChannel");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.amazonaws.mws.entity.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Jewelry }
     * 
     */
    public Jewelry createJewelry() {
        return new Jewelry();
    }

    /**
     * Create an instance of {@link Watch }
     * 
     */
    public Watch createWatch() {
        return new Watch();
    }

    /**
     * Create an instance of {@link FashionEarring }
     * 
     */
    public FashionEarring createFashionEarring() {
        return new FashionEarring();
    }

    /**
     * Create an instance of {@link Product }
     * 
     */
    public Product createProduct() {
        return new Product();
    }

    /**
     * Create an instance of {@link FineNecklaceBraceletAnklet }
     * 
     */
    public FineNecklaceBraceletAnklet createFineNecklaceBraceletAnklet() {
        return new FineNecklaceBraceletAnklet();
    }

    /**
     * Create an instance of {@link FineOther }
     * 
     */
    public FineOther createFineOther() {
        return new FineOther();
    }

    /**
     * Create an instance of {@link AmazonEnvelope }
     * 
     */
    public AmazonEnvelope createAmazonEnvelope() {
        return new AmazonEnvelope();
    }

    /**
     * Create an instance of {@link Price }
     * 
     */
    public Price createPrice() {
        return new Price();
    }

    /**
     * Create an instance of {@link Relationship }
     * 
     */
    public Relationship createRelationship() {
        return new Relationship();
    }

    /**
     * Create an instance of {@link Battery }
     * 
     */
    public Battery createBattery() {
        return new Battery();
    }

    /**
     * Create an instance of {@link FashionNecklaceBraceletAnklet }
     * 
     */
    public FashionNecklaceBraceletAnklet createFashionNecklaceBraceletAnklet() {
        return new FashionNecklaceBraceletAnklet();
    }

    /**
     * Create an instance of {@link FineRing }
     * 
     */
    public FineRing createFineRing() {
        return new FineRing();
    }

    /**
     * Create an instance of {@link FineEarring }
     * 
     */
    public FineEarring createFineEarring() {
        return new FineEarring();
    }

    /**
     * Create an instance of {@link ProcessingReport }
     * 
     */
    public ProcessingReport createProcessingReport() {
        return new ProcessingReport();
    }

    /**
     * Create an instance of {@link SettlementReport }
     * 
     */
    public SettlementReport createSettlementReport() {
        return new SettlementReport();
    }

    /**
     * Create an instance of {@link OrderFulfillment }
     * 
     */
    public OrderFulfillment createOrderFulfillment() {
        return new OrderFulfillment();
    }

    /**
     * Create an instance of {@link OrderAcknowledgement }
     * 
     */
    public OrderAcknowledgement createOrderAcknowledgement() {
        return new OrderAcknowledgement();
    }

    /**
     * Create an instance of {@link Override }
     * 
     */
    public Override createOverride() {
        return new Override();
    }

    /**
     * Create an instance of {@link FashionOther }
     * 
     */
    public FashionOther createFashionOther() {
        return new FashionOther();
    }

    /**
     * Create an instance of {@link FulfillmentCenter }
     * 
     */
    public FulfillmentCenter createFulfillmentCenter() {
        return new FulfillmentCenter();
    }

    /**
     * Create an instance of {@link FashionRing }
     * 
     */
    public FashionRing createFashionRing() {
        return new FashionRing();
    }

    /**
     * Create an instance of {@link OrderAdjustment }
     * 
     */
    public OrderAdjustment createOrderAdjustment() {
        return new OrderAdjustment();
    }

    /**
     * Create an instance of {@link BuyerPrice }
     * 
     */
    public BuyerPrice createBuyerPrice() {
        return new BuyerPrice();
    }

    /**
     * Create an instance of {@link DirectPaymentType }
     * 
     */
    public DirectPaymentType createDirectPaymentType() {
        return new DirectPaymentType();
    }

    /**
     * Create an instance of {@link AmazonFees }
     * 
     */
    public AmazonFees createAmazonFees() {
        return new AmazonFees();
    }

    /**
     * Create an instance of {@link AdjustmentDirectPaymentType }
     * 
     */
    public AdjustmentDirectPaymentType createAdjustmentDirectPaymentType() {
        return new AdjustmentDirectPaymentType();
    }

    /**
     * Create an instance of {@link PromotionDataType }
     * 
     */
    public PromotionDataType createPromotionDataType() {
        return new PromotionDataType();
    }

    /**
     * Create an instance of {@link AdjustmentBuyerPrice }
     * 
     */
    public AdjustmentBuyerPrice createAdjustmentBuyerPrice() {
        return new AdjustmentBuyerPrice();
    }

    /**
     * Create an instance of {@link OrderAdjustment.AdjustedItem }
     * 
     */
    public OrderAdjustment.AdjustedItem createOrderAdjustmentAdjustedItem() {
        return new OrderAdjustment.AdjustedItem();
    }

    /**
     * Create an instance of {@link OrderAdjustment.AdjustedItem.PromotionAdjustments }
     * 
     */
    public OrderAdjustment.AdjustedItem.PromotionAdjustments createOrderAdjustmentAdjustedItemPromotionAdjustments() {
        return new OrderAdjustment.AdjustedItem.PromotionAdjustments();
    }

    /**
     * Create an instance of {@link SettlementReport.Adjustment }
     * 
     */
    public SettlementReport.Adjustment createSettlementReportAdjustment() {
        return new SettlementReport.Adjustment();
    }

    /**
     * Create an instance of {@link SettlementReport.Adjustment.Fulfillment }
     * 
     */
    public SettlementReport.Adjustment.Fulfillment createSettlementReportAdjustmentFulfillment() {
        return new SettlementReport.Adjustment.Fulfillment();
    }

    /**
     * Create an instance of {@link SettlementReport.Adjustment.Fulfillment.AdjustedItem }
     * 
     */
    public SettlementReport.Adjustment.Fulfillment.AdjustedItem createSettlementReportAdjustmentFulfillmentAdjustedItem() {
        return new SettlementReport.Adjustment.Fulfillment.AdjustedItem();
    }

    /**
     * Create an instance of {@link SettlementReport.Order }
     * 
     */
    public SettlementReport.Order createSettlementReportOrder() {
        return new SettlementReport.Order();
    }

    /**
     * Create an instance of {@link SettlementReport.Order.Fulfillment }
     * 
     */
    public SettlementReport.Order.Fulfillment createSettlementReportOrderFulfillment() {
        return new SettlementReport.Order.Fulfillment();
    }

    /**
     * Create an instance of {@link SettlementReport.Order.Fulfillment.Item }
     * 
     */
    public SettlementReport.Order.Fulfillment.Item createSettlementReportOrderFulfillmentItem() {
        return new SettlementReport.Order.Fulfillment.Item();
    }

    /**
     * Create an instance of {@link ProcessingReport.Result }
     * 
     */
    public ProcessingReport.Result createProcessingReportResult() {
        return new ProcessingReport.Result();
    }

    /**
     * Create an instance of {@link JewelryBattery }
     * 
     */
    public JewelryBattery createJewelryBattery() {
        return new JewelryBattery();
    }

    /**
     * Create an instance of {@link AgeRecommendation }
     * 
     */
    public AgeRecommendation createAgeRecommendation() {
        return new AgeRecommendation();
    }

    /**
     * Create an instance of {@link MinimumAgeRecommendedDimension }
     * 
     */
    public MinimumAgeRecommendedDimension createMinimumAgeRecommendedDimension() {
        return new MinimumAgeRecommendedDimension();
    }

    /**
     * Create an instance of {@link AgeRecommendedDimension }
     * 
     */
    public AgeRecommendedDimension createAgeRecommendedDimension() {
        return new AgeRecommendedDimension();
    }

    /**
     * Create an instance of {@link ForwardFacingWeight }
     * 
     */
    public ForwardFacingWeight createForwardFacingWeight() {
        return new ForwardFacingWeight();
    }

    /**
     * Create an instance of {@link WeightDimension }
     * 
     */
    public WeightDimension createWeightDimension() {
        return new WeightDimension();
    }

    /**
     * Create an instance of {@link Inventory }
     * 
     */
    public Inventory createInventory() {
        return new Inventory();
    }

    /**
     * Create an instance of {@link Jewelry.ProductType }
     * 
     */
    public Jewelry.ProductType createJewelryProductType() {
        return new Jewelry.ProductType();
    }

    /**
     * Create an instance of {@link LengthDimension }
     * 
     */
    public LengthDimension createLengthDimension() {
        return new LengthDimension();
    }

    /**
     * Create an instance of {@link VolumeDimension }
     * 
     */
    public VolumeDimension createVolumeDimension() {
        return new VolumeDimension();
    }

    /**
     * Create an instance of {@link Watch.VariationData }
     * 
     */
    public Watch.VariationData createWatchVariationData() {
        return new Watch.VariationData();
    }

    /**
     * Create an instance of {@link PressureDimension }
     * 
     */
    public PressureDimension createPressureDimension() {
        return new PressureDimension();
    }

    /**
     * Create an instance of {@link ColorSpecification }
     * 
     */
    public ColorSpecification createColorSpecification() {
        return new ColorSpecification();
    }

    /**
     * Create an instance of {@link FashionEarring.VariationData }
     * 
     */
    public FashionEarring.VariationData createFashionEarringVariationData() {
        return new FashionEarring.VariationData();
    }

    /**
     * Create an instance of {@link StoneType }
     * 
     */
    public StoneType createStoneType() {
        return new StoneType();
    }

    /**
     * Create an instance of {@link Pearl }
     * 
     */
    public Pearl createPearl() {
        return new Pearl();
    }

    /**
     * Create an instance of {@link CertificateType }
     * 
     */
    public CertificateType createCertificateType() {
        return new CertificateType();
    }

    /**
     * Create an instance of {@link JewelryWeightDimension }
     * 
     */
    public JewelryWeightDimension createJewelryWeightDimension() {
        return new JewelryWeightDimension();
    }

    /**
     * Create an instance of {@link ComputerPlatform }
     * 
     */
    public ComputerPlatform createComputerPlatform() {
        return new ComputerPlatform();
    }

    /**
     * Create an instance of {@link StandardProductID }
     * 
     */
    public StandardProductID createStandardProductID() {
        return new StandardProductID();
    }

    /**
     * Create an instance of {@link RelatedProductID }
     * 
     */
    public RelatedProductID createRelatedProductID() {
        return new RelatedProductID();
    }

    /**
     * Create an instance of {@link ConditionInfo }
     * 
     */
    public ConditionInfo createConditionInfo() {
        return new ConditionInfo();
    }

    /**
     * Create an instance of {@link RebateType }
     * 
     */
    public RebateType createRebateType() {
        return new RebateType();
    }

    /**
     * Create an instance of {@link Product.DescriptionData }
     * 
     */
    public Product.DescriptionData createProductDescriptionData() {
        return new Product.DescriptionData();
    }

    /**
     * Create an instance of {@link Product.PromoTag }
     * 
     */
    public Product.PromoTag createProductPromoTag() {
        return new Product.PromoTag();
    }

    /**
     * Create an instance of {@link Product.DiscoveryData }
     * 
     */
    public Product.DiscoveryData createProductDiscoveryData() {
        return new Product.DiscoveryData();
    }

    /**
     * Create an instance of {@link Product.ProductData }
     * 
     */
    public Product.ProductData createProductProductData() {
        return new Product.ProductData();
    }

    /**
     * Create an instance of {@link FineNecklaceBraceletAnklet.VariationData }
     * 
     */
    public FineNecklaceBraceletAnklet.VariationData createFineNecklaceBraceletAnkletVariationData() {
        return new FineNecklaceBraceletAnklet.VariationData();
    }

    /**
     * Create an instance of {@link FineOther.VariationData }
     * 
     */
    public FineOther.VariationData createFineOtherVariationData() {
        return new FineOther.VariationData();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link AmazonEnvelope.Message }
     * 
     */
    public AmazonEnvelope.Message createAmazonEnvelopeMessage() {
        return new AmazonEnvelope.Message();
    }

    /**
     * Create an instance of {@link OverrideCurrencyAmount }
     * 
     */
    public OverrideCurrencyAmount createOverrideCurrencyAmount() {
        return new OverrideCurrencyAmount();
    }

    /**
     * Create an instance of {@link Price.QuantityPrice }
     * 
     */
    public Price.QuantityPrice createPriceQuantityPrice() {
        return new Price.QuantityPrice();
    }

    /**
     * Create an instance of {@link StringOverrideCurrencyAmount }
     * 
     */
    public StringOverrideCurrencyAmount createStringOverrideCurrencyAmount() {
        return new StringOverrideCurrencyAmount();
    }

    /**
     * Create an instance of {@link CurrencyAmountWithDefault }
     * 
     */
    public CurrencyAmountWithDefault createCurrencyAmountWithDefault() {
        return new CurrencyAmountWithDefault();
    }

    /**
     * Create an instance of {@link Price.Sale }
     * 
     */
    public Price.Sale createPriceSale() {
        return new Price.Sale();
    }

    /**
     * Create an instance of {@link DatedCompareAtPrice }
     * 
     */
    public DatedCompareAtPrice createDatedCompareAtPrice() {
        return new DatedCompareAtPrice();
    }

    /**
     * Create an instance of {@link DatedPrice }
     * 
     */
    public DatedPrice createDatedPrice() {
        return new DatedPrice();
    }

    /**
     * Create an instance of {@link Price.Rental0 }
     * 
     */
    public Price.Rental0 createPriceRental0() {
        return new Price.Rental0();
    }

    /**
     * Create an instance of {@link Price.Rental1 }
     * 
     */
    public Price.Rental1 createPriceRental1() {
        return new Price.Rental1();
    }

    /**
     * Create an instance of {@link Price.Rental2 }
     * 
     */
    public Price.Rental2 createPriceRental2() {
        return new Price.Rental2();
    }

    /**
     * Create an instance of {@link Price.Rental3 }
     * 
     */
    public Price.Rental3 createPriceRental3() {
        return new Price.Rental3();
    }

    /**
     * Create an instance of {@link Price.Rental4 }
     * 
     */
    public Price.Rental4 createPriceRental4() {
        return new Price.Rental4();
    }

    /**
     * Create an instance of {@link Price.Rental5 }
     * 
     */
    public Price.Rental5 createPriceRental5() {
        return new Price.Rental5();
    }

    /**
     * Create an instance of {@link Price.Rental6 }
     * 
     */
    public Price.Rental6 createPriceRental6() {
        return new Price.Rental6();
    }

    /**
     * Create an instance of {@link Price.Rental7 }
     * 
     */
    public Price.Rental7 createPriceRental7() {
        return new Price.Rental7();
    }

    /**
     * Create an instance of {@link Price.Rental8 }
     * 
     */
    public Price.Rental8 createPriceRental8() {
        return new Price.Rental8();
    }

    /**
     * Create an instance of {@link Price.Rental9 }
     * 
     */
    public Price.Rental9 createPriceRental9() {
        return new Price.Rental9();
    }

    /**
     * Create an instance of {@link Relationship.Relation }
     * 
     */
    public Relationship.Relation createRelationshipRelation() {
        return new Relationship.Relation();
    }

    /**
     * Create an instance of {@link Battery.BatterySubgroup }
     * 
     */
    public Battery.BatterySubgroup createBatteryBatterySubgroup() {
        return new Battery.BatterySubgroup();
    }

    /**
     * Create an instance of {@link FashionNecklaceBraceletAnklet.VariationData }
     * 
     */
    public FashionNecklaceBraceletAnklet.VariationData createFashionNecklaceBraceletAnkletVariationData() {
        return new FashionNecklaceBraceletAnklet.VariationData();
    }

    /**
     * Create an instance of {@link FineRing.VariationData }
     * 
     */
    public FineRing.VariationData createFineRingVariationData() {
        return new FineRing.VariationData();
    }

    /**
     * Create an instance of {@link CharacterDataType }
     * 
     */
    public CharacterDataType createCharacterDataType() {
        return new CharacterDataType();
    }

    /**
     * Create an instance of {@link FineEarring.VariationData }
     * 
     */
    public FineEarring.VariationData createFineEarringVariationData() {
        return new FineEarring.VariationData();
    }

    /**
     * Create an instance of {@link ProcessingReport.ProcessingSummary }
     * 
     */
    public ProcessingReport.ProcessingSummary createProcessingReportProcessingSummary() {
        return new ProcessingReport.ProcessingSummary();
    }

    /**
     * Create an instance of {@link HeightRecommendation }
     * 
     */
    public HeightRecommendation createHeightRecommendation() {
        return new HeightRecommendation();
    }

    /**
     * Create an instance of {@link WeightRecommendation }
     * 
     */
    public WeightRecommendation createWeightRecommendation() {
        return new WeightRecommendation();
    }

    /**
     * Create an instance of {@link WeightIntegerDimension }
     * 
     */
    public WeightIntegerDimension createWeightIntegerDimension() {
        return new WeightIntegerDimension();
    }

    /**
     * Create an instance of {@link SettlementReport.SettlementData }
     * 
     */
    public SettlementReport.SettlementData createSettlementReportSettlementData() {
        return new SettlementReport.SettlementData();
    }

    /**
     * Create an instance of {@link SettlementReport.OtherFee }
     * 
     */
    public SettlementReport.OtherFee createSettlementReportOtherFee() {
        return new SettlementReport.OtherFee();
    }

    /**
     * Create an instance of {@link SettlementReport.OtherTransaction }
     * 
     */
    public SettlementReport.OtherTransaction createSettlementReportOtherTransaction() {
        return new SettlementReport.OtherTransaction();
    }

    /**
     * Create an instance of {@link SettlementReport.MiscEvent }
     * 
     */
    public SettlementReport.MiscEvent createSettlementReportMiscEvent() {
        return new SettlementReport.MiscEvent();
    }

    /**
     * Create an instance of {@link OrderFulfillment.FulfillmentData }
     * 
     */
    public OrderFulfillment.FulfillmentData createOrderFulfillmentFulfillmentData() {
        return new OrderFulfillment.FulfillmentData();
    }

    /**
     * Create an instance of {@link OrderFulfillment.Item }
     * 
     */
    public OrderFulfillment.Item createOrderFulfillmentItem() {
        return new OrderFulfillment.Item();
    }

    /**
     * Create an instance of {@link OrderAcknowledgement.Item }
     * 
     */
    public OrderAcknowledgement.Item createOrderAcknowledgementItem() {
        return new OrderAcknowledgement.Item();
    }

    /**
     * Create an instance of {@link Listings }
     * 
     */
    public Listings createListings() {
        return new Listings();
    }

    /**
     * Create an instance of {@link ProductImage }
     * 
     */
    public ProductImage createProductImage() {
        return new ProductImage();
    }

    /**
     * Create an instance of {@link Override.ShippingOverride }
     * 
     */
    public Override.ShippingOverride createOverrideShippingOverride() {
        return new Override.ShippingOverride();
    }

    /**
     * Create an instance of {@link FashionOther.VariationData }
     * 
     */
    public FashionOther.VariationData createFashionOtherVariationData() {
        return new FashionOther.VariationData();
    }

    /**
     * Create an instance of {@link RearFacingWeight }
     * 
     */
    public RearFacingWeight createRearFacingWeight() {
        return new RearFacingWeight();
    }

    /**
     * Create an instance of {@link Recall }
     * 
     */
    public Recall createRecall() {
        return new Recall();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link ShoulderHarnessHeight }
     * 
     */
    public ShoulderHarnessHeight createShoulderHarnessHeight() {
        return new ShoulderHarnessHeight();
    }

    /**
     * Create an instance of {@link FulfillmentCenter.OperatingHours }
     * 
     */
    public FulfillmentCenter.OperatingHours createFulfillmentCenterOperatingHours() {
        return new FulfillmentCenter.OperatingHours();
    }

    /**
     * Create an instance of {@link FashionRing.VariationData }
     * 
     */
    public FashionRing.VariationData createFashionRingVariationData() {
        return new FashionRing.VariationData();
    }

    /**
     * Create an instance of {@link ResolutionDimension }
     * 
     */
    public ResolutionDimension createResolutionDimension() {
        return new ResolutionDimension();
    }

    /**
     * Create an instance of {@link LoyaltyCustomAttribute }
     * 
     */
    public LoyaltyCustomAttribute createLoyaltyCustomAttribute() {
        return new LoyaltyCustomAttribute();
    }

    /**
     * Create an instance of {@link DensityDimension }
     * 
     */
    public DensityDimension createDensityDimension() {
        return new DensityDimension();
    }

    /**
     * Create an instance of {@link VoltageDecimalDimension }
     * 
     */
    public VoltageDecimalDimension createVoltageDecimalDimension() {
        return new VoltageDecimalDimension();
    }

    /**
     * Create an instance of {@link CapacityUnit }
     * 
     */
    public CapacityUnit createCapacityUnit() {
        return new CapacityUnit();
    }

    /**
     * Create an instance of {@link CycleLengthDimension }
     * 
     */
    public CycleLengthDimension createCycleLengthDimension() {
        return new CycleLengthDimension();
    }

    /**
     * Create an instance of {@link NoiseLevelDimension }
     * 
     */
    public NoiseLevelDimension createNoiseLevelDimension() {
        return new NoiseLevelDimension();
    }

    /**
     * Create an instance of {@link MemorySizeDimension }
     * 
     */
    public MemorySizeDimension createMemorySizeDimension() {
        return new MemorySizeDimension();
    }

    /**
     * Create an instance of {@link HardnessDimension }
     * 
     */
    public HardnessDimension createHardnessDimension() {
        return new HardnessDimension();
    }

    /**
     * Create an instance of {@link AmperageDimension }
     * 
     */
    public AmperageDimension createAmperageDimension() {
        return new AmperageDimension();
    }

    /**
     * Create an instance of {@link AlcoholContentDimension }
     * 
     */
    public AlcoholContentDimension createAlcoholContentDimension() {
        return new AlcoholContentDimension();
    }

    /**
     * Create an instance of {@link BatteryPowerDimension }
     * 
     */
    public BatteryPowerDimension createBatteryPowerDimension() {
        return new BatteryPowerDimension();
    }

    /**
     * Create an instance of {@link TemperatureRatingDimension }
     * 
     */
    public TemperatureRatingDimension createTemperatureRatingDimension() {
        return new TemperatureRatingDimension();
    }

    /**
     * Create an instance of {@link OperatingHoursBase }
     * 
     */
    public OperatingHoursBase createOperatingHoursBase() {
        return new OperatingHoursBase();
    }

    /**
     * Create an instance of {@link WattageDimensionOptionalUnit }
     * 
     */
    public WattageDimensionOptionalUnit createWattageDimensionOptionalUnit() {
        return new WattageDimensionOptionalUnit();
    }

    /**
     * Create an instance of {@link LuminiousIntensityDimension }
     * 
     */
    public LuminiousIntensityDimension createLuminiousIntensityDimension() {
        return new LuminiousIntensityDimension();
    }

    /**
     * Create an instance of {@link StringLengthOptionalDimension }
     * 
     */
    public StringLengthOptionalDimension createStringLengthOptionalDimension() {
        return new StringLengthOptionalDimension();
    }

    /**
     * Create an instance of {@link Dimensions }
     * 
     */
    public Dimensions createDimensions() {
        return new Dimensions();
    }

    /**
     * Create an instance of {@link SpeedDimension }
     * 
     */
    public SpeedDimension createSpeedDimension() {
        return new SpeedDimension();
    }

    /**
     * Create an instance of {@link MemorySizeIntegerDimension }
     * 
     */
    public MemorySizeIntegerDimension createMemorySizeIntegerDimension() {
        return new MemorySizeIntegerDimension();
    }

    /**
     * Create an instance of {@link SunProtectionDimension }
     * 
     */
    public SunProtectionDimension createSunProtectionDimension() {
        return new SunProtectionDimension();
    }

    /**
     * Create an instance of {@link WattageDimension }
     * 
     */
    public WattageDimension createWattageDimension() {
        return new WattageDimension();
    }

    /**
     * Create an instance of {@link ZoomDimension }
     * 
     */
    public ZoomDimension createZoomDimension() {
        return new ZoomDimension();
    }

    /**
     * Create an instance of {@link FrequencyIntegerDimension }
     * 
     */
    public FrequencyIntegerDimension createFrequencyIntegerDimension() {
        return new FrequencyIntegerDimension();
    }

    /**
     * Create an instance of {@link ClothingSizeDimension }
     * 
     */
    public ClothingSizeDimension createClothingSizeDimension() {
        return new ClothingSizeDimension();
    }

    /**
     * Create an instance of {@link OptionalResolutionDimension }
     * 
     */
    public OptionalResolutionDimension createOptionalResolutionDimension() {
        return new OptionalResolutionDimension();
    }

    /**
     * Create an instance of {@link VolumeRateDimension }
     * 
     */
    public VolumeRateDimension createVolumeRateDimension() {
        return new VolumeRateDimension();
    }

    /**
     * Create an instance of {@link BootSizeDimension }
     * 
     */
    public BootSizeDimension createBootSizeDimension() {
        return new BootSizeDimension();
    }

    /**
     * Create an instance of {@link CurencyDimension }
     * 
     */
    public CurencyDimension createCurencyDimension() {
        return new CurencyDimension();
    }

    /**
     * Create an instance of {@link OverrideCurrencyAmountWithTax }
     * 
     */
    public OverrideCurrencyAmountWithTax createOverrideCurrencyAmountWithTax() {
        return new OverrideCurrencyAmountWithTax();
    }

    /**
     * Create an instance of {@link TorqueType }
     * 
     */
    public TorqueType createTorqueType() {
        return new TorqueType();
    }

    /**
     * Create an instance of {@link BatteryPowerIntegerDimension }
     * 
     */
    public BatteryPowerIntegerDimension createBatteryPowerIntegerDimension() {
        return new BatteryPowerIntegerDimension();
    }

    /**
     * Create an instance of {@link AirFlowDisplacementDimension }
     * 
     */
    public AirFlowDisplacementDimension createAirFlowDisplacementDimension() {
        return new AirFlowDisplacementDimension();
    }

    /**
     * Create an instance of {@link OptionalMagnificationDimension }
     * 
     */
    public OptionalMagnificationDimension createOptionalMagnificationDimension() {
        return new OptionalMagnificationDimension();
    }

    /**
     * Create an instance of {@link StringCurrencyAmountWithDefault }
     * 
     */
    public StringCurrencyAmountWithDefault createStringCurrencyAmountWithDefault() {
        return new StringCurrencyAmountWithDefault();
    }

    /**
     * Create an instance of {@link PhoneNumberType }
     * 
     */
    public PhoneNumberType createPhoneNumberType() {
        return new PhoneNumberType();
    }

    /**
     * Create an instance of {@link SpatialDimensions }
     * 
     */
    public SpatialDimensions createSpatialDimensions() {
        return new SpatialDimensions();
    }

    /**
     * Create an instance of {@link StringTimeDimension }
     * 
     */
    public StringTimeDimension createStringTimeDimension() {
        return new StringTimeDimension();
    }

    /**
     * Create an instance of {@link TimeIntegerDimension }
     * 
     */
    public TimeIntegerDimension createTimeIntegerDimension() {
        return new TimeIntegerDimension();
    }

    /**
     * Create an instance of {@link CustomizationInfoType }
     * 
     */
    public CustomizationInfoType createCustomizationInfoType() {
        return new CustomizationInfoType();
    }

    /**
     * Create an instance of {@link DegreeDimension }
     * 
     */
    public DegreeDimension createDegreeDimension() {
        return new DegreeDimension();
    }

    /**
     * Create an instance of {@link BatteryLifeDimension }
     * 
     */
    public BatteryLifeDimension createBatteryLifeDimension() {
        return new BatteryLifeDimension();
    }

    /**
     * Create an instance of {@link JewelryLengthDimension }
     * 
     */
    public JewelryLengthDimension createJewelryLengthDimension() {
        return new JewelryLengthDimension();
    }

    /**
     * Create an instance of {@link Customer }
     * 
     */
    public Customer createCustomer() {
        return new Customer();
    }

    /**
     * Create an instance of {@link PositiveWeightDimension }
     * 
     */
    public PositiveWeightDimension createPositiveWeightDimension() {
        return new PositiveWeightDimension();
    }

    /**
     * Create an instance of {@link LuminancePositiveIntegerDimension }
     * 
     */
    public LuminancePositiveIntegerDimension createLuminancePositiveIntegerDimension() {
        return new LuminancePositiveIntegerDimension();
    }

    /**
     * Create an instance of {@link NameValuePair }
     * 
     */
    public NameValuePair createNameValuePair() {
        return new NameValuePair();
    }

    /**
     * Create an instance of {@link MillimeterDecimalDimension }
     * 
     */
    public MillimeterDecimalDimension createMillimeterDecimalDimension() {
        return new MillimeterDecimalDimension();
    }

    /**
     * Create an instance of {@link VolumeAndVolumeRateDimension }
     * 
     */
    public VolumeAndVolumeRateDimension createVolumeAndVolumeRateDimension() {
        return new VolumeAndVolumeRateDimension();
    }

    /**
     * Create an instance of {@link ServingDimension }
     * 
     */
    public ServingDimension createServingDimension() {
        return new ServingDimension();
    }

    /**
     * Create an instance of {@link SweetnessAtHarvestDimension }
     * 
     */
    public SweetnessAtHarvestDimension createSweetnessAtHarvestDimension() {
        return new SweetnessAtHarvestDimension();
    }

    /**
     * Create an instance of {@link DateIntegerDimension }
     * 
     */
    public DateIntegerDimension createDateIntegerDimension() {
        return new DateIntegerDimension();
    }

    /**
     * Create an instance of {@link VoltageIntegerDimensionOptionalUnit }
     * 
     */
    public VoltageIntegerDimensionOptionalUnit createVoltageIntegerDimensionOptionalUnit() {
        return new VoltageIntegerDimensionOptionalUnit();
    }

    /**
     * Create an instance of {@link StringTemperatureDimension }
     * 
     */
    public StringTemperatureDimension createStringTemperatureDimension() {
        return new StringTemperatureDimension();
    }

    /**
     * Create an instance of {@link VoltageIntegerDimension }
     * 
     */
    public VoltageIntegerDimension createVoltageIntegerDimension() {
        return new VoltageIntegerDimension();
    }

    /**
     * Create an instance of {@link MagnificationDimension }
     * 
     */
    public MagnificationDimension createMagnificationDimension() {
        return new MagnificationDimension();
    }

    /**
     * Create an instance of {@link CurrentDimension }
     * 
     */
    public CurrentDimension createCurrentDimension() {
        return new CurrentDimension();
    }

    /**
     * Create an instance of {@link AreaDimension }
     * 
     */
    public AreaDimension createAreaDimension() {
        return new AreaDimension();
    }

    /**
     * Create an instance of {@link SubscriptionTermDimension }
     * 
     */
    public SubscriptionTermDimension createSubscriptionTermDimension() {
        return new SubscriptionTermDimension();
    }

    /**
     * Create an instance of {@link WeightRecommendationType }
     * 
     */
    public WeightRecommendationType createWeightRecommendationType() {
        return new WeightRecommendationType();
    }

    /**
     * Create an instance of {@link EnergyRatingType }
     * 
     */
    public EnergyRatingType createEnergyRatingType() {
        return new EnergyRatingType();
    }

    /**
     * Create an instance of {@link OpticalPowerDimension }
     * 
     */
    public OpticalPowerDimension createOpticalPowerDimension() {
        return new OpticalPowerDimension();
    }

    /**
     * Create an instance of {@link WattageIntegerDimension }
     * 
     */
    public WattageIntegerDimension createWattageIntegerDimension() {
        return new WattageIntegerDimension();
    }

    /**
     * Create an instance of {@link LuminanceDimension }
     * 
     */
    public LuminanceDimension createLuminanceDimension() {
        return new LuminanceDimension();
    }

    /**
     * Create an instance of {@link AddressTypeSupportNonCity }
     * 
     */
    public AddressTypeSupportNonCity createAddressTypeSupportNonCity() {
        return new AddressTypeSupportNonCity();
    }

    /**
     * Create an instance of {@link PowerDimension }
     * 
     */
    public PowerDimension createPowerDimension() {
        return new PowerDimension();
    }

    /**
     * Create an instance of {@link BurnTimeDimension }
     * 
     */
    public BurnTimeDimension createBurnTimeDimension() {
        return new BurnTimeDimension();
    }

    /**
     * Create an instance of {@link ApertureDimension }
     * 
     */
    public ApertureDimension createApertureDimension() {
        return new ApertureDimension();
    }

    /**
     * Create an instance of {@link LengthIntegerDimension }
     * 
     */
    public LengthIntegerDimension createLengthIntegerDimension() {
        return new LengthIntegerDimension();
    }

    /**
     * Create an instance of {@link PositiveNonZeroWeightDimension }
     * 
     */
    public PositiveNonZeroWeightDimension createPositiveNonZeroWeightDimension() {
        return new PositiveNonZeroWeightDimension();
    }

    /**
     * Create an instance of {@link VolumeIntegerDimension }
     * 
     */
    public VolumeIntegerDimension createVolumeIntegerDimension() {
        return new VolumeIntegerDimension();
    }

    /**
     * Create an instance of {@link LengthDimensionOptionalUnit }
     * 
     */
    public LengthDimensionOptionalUnit createLengthDimensionOptionalUnit() {
        return new LengthDimensionOptionalUnit();
    }

    /**
     * Create an instance of {@link ResistanceDimension }
     * 
     */
    public ResistanceDimension createResistanceDimension() {
        return new ResistanceDimension();
    }

    /**
     * Create an instance of {@link GraduationInterval }
     * 
     */
    public GraduationInterval createGraduationInterval() {
        return new GraduationInterval();
    }

    /**
     * Create an instance of {@link EnergyConsumptionDimension }
     * 
     */
    public EnergyConsumptionDimension createEnergyConsumptionDimension() {
        return new EnergyConsumptionDimension();
    }

    /**
     * Create an instance of {@link NeckSizeDimension }
     * 
     */
    public NeckSizeDimension createNeckSizeDimension() {
        return new NeckSizeDimension();
    }

    /**
     * Create an instance of {@link CurrencyAmount }
     * 
     */
    public CurrencyAmount createCurrencyAmount() {
        return new CurrencyAmount();
    }

    /**
     * Create an instance of {@link AssemblyTimeDimension }
     * 
     */
    public AssemblyTimeDimension createAssemblyTimeDimension() {
        return new AssemblyTimeDimension();
    }

    /**
     * Create an instance of {@link ForceDimension }
     * 
     */
    public ForceDimension createForceDimension() {
        return new ForceDimension();
    }

    /**
     * Create an instance of {@link FrequencyDimension }
     * 
     */
    public FrequencyDimension createFrequencyDimension() {
        return new FrequencyDimension();
    }

    /**
     * Create an instance of {@link StringLengthDimension }
     * 
     */
    public StringLengthDimension createStringLengthDimension() {
        return new StringLengthDimension();
    }

    /**
     * Create an instance of {@link TimeDimension }
     * 
     */
    public TimeDimension createTimeDimension() {
        return new TimeDimension();
    }

    /**
     * Create an instance of {@link AdjustmentCurrencyAmount }
     * 
     */
    public AdjustmentCurrencyAmount createAdjustmentCurrencyAmount() {
        return new AdjustmentCurrencyAmount();
    }

    /**
     * Create an instance of {@link AreaDimensionOptionalUnit }
     * 
     */
    public AreaDimensionOptionalUnit createAreaDimensionOptionalUnit() {
        return new AreaDimensionOptionalUnit();
    }

    /**
     * Create an instance of {@link ContinuousShootingDimension }
     * 
     */
    public ContinuousShootingDimension createContinuousShootingDimension() {
        return new ContinuousShootingDimension();
    }

    /**
     * Create an instance of {@link TemperatureDimension }
     * 
     */
    public TemperatureDimension createTemperatureDimension() {
        return new TemperatureDimension();
    }

    /**
     * Create an instance of {@link LuminanceIntegerDimension }
     * 
     */
    public LuminanceIntegerDimension createLuminanceIntegerDimension() {
        return new LuminanceIntegerDimension();
    }

    /**
     * Create an instance of {@link PixelDimension }
     * 
     */
    public PixelDimension createPixelDimension() {
        return new PixelDimension();
    }

    /**
     * Create an instance of {@link VineyardYieldDimension }
     * 
     */
    public VineyardYieldDimension createVineyardYieldDimension() {
        return new VineyardYieldDimension();
    }

    /**
     * Create an instance of {@link OptionalLengthIntegerDimension }
     * 
     */
    public OptionalLengthIntegerDimension createOptionalLengthIntegerDimension() {
        return new OptionalLengthIntegerDimension();
    }

    /**
     * Create an instance of {@link EmailAddressType }
     * 
     */
    public EmailAddressType createEmailAddressType() {
        return new EmailAddressType();
    }

    /**
     * Create an instance of {@link PositiveCurrencyAmount }
     * 
     */
    public PositiveCurrencyAmount createPositiveCurrencyAmount() {
        return new PositiveCurrencyAmount();
    }

    /**
     * Create an instance of {@link BuyerPrice.Component }
     * 
     */
    public BuyerPrice.Component createBuyerPriceComponent() {
        return new BuyerPrice.Component();
    }

    /**
     * Create an instance of {@link DirectPaymentType.Component }
     * 
     */
    public DirectPaymentType.Component createDirectPaymentTypeComponent() {
        return new DirectPaymentType.Component();
    }

    /**
     * Create an instance of {@link AmazonFees.Fee }
     * 
     */
    public AmazonFees.Fee createAmazonFeesFee() {
        return new AmazonFees.Fee();
    }

    /**
     * Create an instance of {@link AdjustmentDirectPaymentType.Component }
     * 
     */
    public AdjustmentDirectPaymentType.Component createAdjustmentDirectPaymentTypeComponent() {
        return new AdjustmentDirectPaymentType.Component();
    }

    /**
     * Create an instance of {@link PromotionDataType.Component }
     * 
     */
    public PromotionDataType.Component createPromotionDataTypeComponent() {
        return new PromotionDataType.Component();
    }

    /**
     * Create an instance of {@link AdjustmentBuyerPrice.Component }
     * 
     */
    public AdjustmentBuyerPrice.Component createAdjustmentBuyerPriceComponent() {
        return new AdjustmentBuyerPrice.Component();
    }

    /**
     * Create an instance of {@link OrderAdjustment.AdjustedItem.PromotionAdjustments.Component }
     * 
     */
    public OrderAdjustment.AdjustedItem.PromotionAdjustments.Component createOrderAdjustmentAdjustedItemPromotionAdjustmentsComponent() {
        return new OrderAdjustment.AdjustedItem.PromotionAdjustments.Component();
    }

    /**
     * Create an instance of {@link SettlementReport.Adjustment.Fulfillment.AdjustedItem.PromotionAdjustment }
     * 
     */
    public SettlementReport.Adjustment.Fulfillment.AdjustedItem.PromotionAdjustment createSettlementReportAdjustmentFulfillmentAdjustedItemPromotionAdjustment() {
        return new SettlementReport.Adjustment.Fulfillment.AdjustedItem.PromotionAdjustment();
    }

    /**
     * Create an instance of {@link SettlementReport.Order.Fulfillment.Item.Promotion }
     * 
     */
    public SettlementReport.Order.Fulfillment.Item.Promotion createSettlementReportOrderFulfillmentItemPromotion() {
        return new SettlementReport.Order.Fulfillment.Item.Promotion();
    }

    /**
     * Create an instance of {@link ProcessingReport.Result.AdditionalInfo }
     * 
     */
    public ProcessingReport.Result.AdditionalInfo createProcessingReportResultAdditionalInfo() {
        return new ProcessingReport.Result.AdditionalInfo();
    }

    /**
     * Create an instance of {@link JewelryBattery.BatterySubgroup }
     * 
     */
    public JewelryBattery.BatterySubgroup createJewelryBatteryBatterySubgroup() {
        return new JewelryBattery.BatterySubgroup();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ConditionType")
    public JAXBElement<String> createConditionType(String value) {
        return new JAXBElement<String>(_ConditionType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AmazonOrderItemCode")
    public JAXBElement<String> createAmazonOrderItemCode(String value) {
        return new JAXBElement<String>(_AmazonOrderItemCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ProductTaxCode")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createProductTaxCode(String value) {
        return new JAXBElement<String>(_ProductTaxCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CharacterDataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CharacterData")
    public JAXBElement<CharacterDataType> createCharacterData(CharacterDataType value) {
        return new JAXBElement<CharacterDataType>(_CharacterData_QNAME, CharacterDataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AmazonOrderID")
    public JAXBElement<String> createAmazonOrderID(String value) {
        return new JAXBElement<String>(_AmazonOrderID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MerchantOrderItemID")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createMerchantOrderItemID(String value) {
        return new JAXBElement<String>(_MerchantOrderItemID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Denomination")
    public JAXBElement<BigDecimal> createDenomination(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Denomination_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MerchantPromotionID")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createMerchantPromotionID(String value) {
        return new JAXBElement<String>(_MerchantPromotionID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SKU")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createSKU(String value) {
        return new JAXBElement<String>(_SKU_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AmazonCustomerID")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createAmazonCustomerID(String value) {
        return new JAXBElement<String>(_AmazonCustomerID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ColorMap")
    public JAXBElement<String> createColorMap(String value) {
        return new JAXBElement<String>(_ColorMap_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ShipmentID")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createShipmentID(String value) {
        return new JAXBElement<String>(_ShipmentID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MerchantFulfillmentID")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createMerchantFulfillmentID(String value) {
        return new JAXBElement<String>(_MerchantFulfillmentID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CarrierCode")
    public JAXBElement<String> createCarrierCode(String value) {
        return new JAXBElement<String>(_CarrierCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FulfillmentMethod")
    public JAXBElement<String> createFulfillmentMethod(String value) {
        return new JAXBElement<String>(_FulfillmentMethod_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FulfillmentCenterID")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createFulfillmentCenterID(String value) {
        return new JAXBElement<String>(_FulfillmentCenterID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PromotionClaimCode")
    public JAXBElement<String> createPromotionClaimCode(String value) {
        return new JAXBElement<String>(_PromotionClaimCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ShipOption")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createShipOption(String value) {
        return new JAXBElement<String>(_ShipOption_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ExternalCustomerID")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createExternalCustomerID(String value) {
        return new JAXBElement<String>(_ExternalCustomerID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddressType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Address")
    public JAXBElement<AddressType> createAddress(AddressType value) {
        return new JAXBElement<AddressType>(_Address_QNAME, AddressType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MarketplaceName")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createMarketplaceName(String value) {
        return new JAXBElement<String>(_MarketplaceName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MerchantOrderID")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createMerchantOrderID(String value) {
        return new JAXBElement<String>(_MerchantOrderID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FulfillmentServiceLevel")
    public JAXBElement<String> createFulfillmentServiceLevel(String value) {
        return new JAXBElement<String>(_FulfillmentServiceLevel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DeliveryChannel")
    public JAXBElement<String> createDeliveryChannel(String value) {
        return new JAXBElement<String>(_DeliveryChannel_QNAME, String.class, null, value);
    }

}
