//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.29 at 10:21:45 PM CST 
//


package com.amazonaws.mws.entity.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ParentSKU" type="{}SKUType"/>
 *         &lt;element name="Relation" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}SKU"/>
 *                   &lt;element name="Type">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="Variation"/>
 *                         &lt;enumeration value="DisplaySet"/>
 *                         &lt;enumeration value="Collection"/>
 *                         &lt;enumeration value="Accessory"/>
 *                         &lt;enumeration value="Customized"/>
 *                         &lt;enumeration value="Part"/>
 *                         &lt;enumeration value="Complements"/>
 *                         &lt;enumeration value="Piece"/>
 *                         &lt;enumeration value="Necessary"/>
 *                         &lt;enumeration value="ReplacementPart"/>
 *                         &lt;enumeration value="Similar"/>
 *                         &lt;enumeration value="Episode"/>
 *                         &lt;enumeration value="Season"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "parentSKU",
    "relation"
})
@XmlRootElement(name = "Relationship")
public class Relationship {

    @XmlElement(name = "ParentSKU", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String parentSKU;
    @XmlElement(name = "Relation", required = true)
    protected List<Relationship.Relation> relation;

    /**
     * Gets the value of the parentSKU property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentSKU() {
        return parentSKU;
    }

    /**
     * Sets the value of the parentSKU property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentSKU(String value) {
        this.parentSKU = value;
    }

    /**
     * Gets the value of the relation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Relationship.Relation }
     * 
     * 
     */
    public List<Relationship.Relation> getRelation() {
        if (relation == null) {
            relation = new ArrayList<Relationship.Relation>();
        }
        return this.relation;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}SKU"/>
     *         &lt;element name="Type">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="Variation"/>
     *               &lt;enumeration value="DisplaySet"/>
     *               &lt;enumeration value="Collection"/>
     *               &lt;enumeration value="Accessory"/>
     *               &lt;enumeration value="Customized"/>
     *               &lt;enumeration value="Part"/>
     *               &lt;enumeration value="Complements"/>
     *               &lt;enumeration value="Piece"/>
     *               &lt;enumeration value="Necessary"/>
     *               &lt;enumeration value="ReplacementPart"/>
     *               &lt;enumeration value="Similar"/>
     *               &lt;enumeration value="Episode"/>
     *               &lt;enumeration value="Season"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "sku",
        "type"
    })
    public static class Relation {

        @XmlElement(name = "SKU", required = true)
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String sku;
        @XmlElement(name = "Type", required = true)
        protected String type;

        /**
         * Gets the value of the sku property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSKU() {
            return sku;
        }

        /**
         * Sets the value of the sku property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSKU(String value) {
            this.sku = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

    }

}
