//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.29 at 10:21:45 PM CST 
//


package com.amazonaws.mws.entity.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TemperatureRatingUnitOfMeasure.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TemperatureRatingUnitOfMeasure">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="degrees-celsius"/>
 *     &lt;enumeration value="degrees-fahrenheit"/>
 *     &lt;enumeration value="kelvin"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TemperatureRatingUnitOfMeasure")
@XmlEnum
public enum TemperatureRatingUnitOfMeasure {

    @XmlEnumValue("degrees-celsius")
    DEGREES_CELSIUS("degrees-celsius"),
    @XmlEnumValue("degrees-fahrenheit")
    DEGREES_FAHRENHEIT("degrees-fahrenheit"),
    @XmlEnumValue("kelvin")
    KELVIN("kelvin");
    private final String value;

    TemperatureRatingUnitOfMeasure(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TemperatureRatingUnitOfMeasure fromValue(String v) {
        for (TemperatureRatingUnitOfMeasure c: TemperatureRatingUnitOfMeasure.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
